const Login_Action_types = {
  LOGIN_WITH_FB: "LOGIN_WITH_FB",
  LOGIN_WITH_FB_SUCCESS: "LOGIN_WITH_FB_SUCCESS",
  LOGIN_WITH_FB_FAILURE: "LOGIN_WITH_FB_FAILURE",
  IS_FETCH_COMPLETED: "IS_FETCH_COMPLETED",
  RELOAD_DATA: "RELOAD_DATA",
};

export default Login_Action_types;
