const Fetch_Users_From_Sqlite = {
  FETCH_USERS_FROM_SQLITE: "FETCH_USERS_FROM_SQLITE",
  FETCH_USERS_FROM_SQLITE_SUCCESS: "FETCH_USERS_FROM_SQLITE_SUCCESS",
  FETCH_USERS_FROM_SQLITE_FAILURE: "FETCH_USERS_FROM_SQLITE_FAILURE",
  RELOAD_DATA: "RELOAD_DATA",
};

export default Fetch_Users_From_Sqlite;
